// Mistral Vibe runtime plugin: writes a run configuration (.vibe/config.toml with only the broker as MCP server and
// only its three tools enabled) and AGENTS.md into the run directory, refusing to overwrite, then starts `vibe` there.
// Headless it runs `vibe -p --output streaming` and keeps what Vibe streams, with the time it arrived, as the run's
// private log (vibe-stream.jsonl): Vibe's own session log has no time per message, and a timeline needs one.
import { spawn, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { publicPath } from "../core/src/public-path.mjs";
import { askVibe } from "./acp.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
/** The MCP server's name in Vibe: its tools are published as `aas_<tool>` (Vibe prefixes the server name). */
export const SERVER = "aas";
/** The file headless sessions stream into, in the run directory. */
export const STREAM_FILE = "vibe-stream.jsonl";
let interruptChild = null;

import { vibeHome } from "./export-stream.mjs";
export { vibeHome };
/** The three tools the agent may use, as Vibe names them. */
export const toolNames = (gameId) => ["documentation", "screenshot", "exec"].map((t) => `${SERVER}_${gameId}_${t}`);

/** A TOML string: JSON's escapes are TOML's for a basic string. */
const tomlString = (v) => JSON.stringify(String(v));

/**
 * The run's configuration. Only the broker is an MCP server, and only its three tools are enabled (the same three are
 * named on the command line at the start). `model` and `effort` are Vibe's own words: `active_model` is a model alias
 * as Vibe lists it, and `thinking` is set on that model's entry, which Vibe merges into its own by alias.
 */
export function renderConfig(broker, { model = null, effort = null, placeholders = false } = {}) {
  const pub = (v) => (placeholders ? publicPath(String(v), broker) : String(v));
  const HARNESS_ENV = new Set(["AAS_GAME_MODULE", "AAS_RUN_DIR", "AAS_ALLOWED_ENDPOINTS", "AAS_TIME_ZONE"]);
  const lines = [
    "# AAS run configuration for Mistral Vibe. Generated by `aas configure --runtime mistral-vibe`;",
    "# machine paths are replaced with __RUN_DIR__ etc. when published as runtime-config/.",
    `enabled_tools = [${toolNames(broker.gameId).map(tomlString).join(", ")}]`,
    ...(model ? [`active_model = ${tomlString(model)}`] : []),
    ...(model && effort ? ["", "[[models]]", `alias = ${tomlString(model)}`, `thinking = ${tomlString(effort)}`] : []),
    "",
    "# The AAS broker. Node permission flags limit filesystem writes to the run directory and reads to core plus the",
    "# game plugin; hardening.mjs limits its network access to the game's endpoint(s).",
    "[[mcp_servers]]",
    `name = ${tomlString(SERVER)}`,
    'transport = "stdio"',
    'command = "node"',
    `args = [${broker.nodeArgs.map((a) => tomlString(pub(a))).join(", ")}]`,
    `cwd = ${tomlString(pub(broker.runDir))}`,
    "",
    "[mcp_servers.env]",
    ...Object.entries(broker.env).map(([k, v]) => `${k} = ${tomlString(placeholders && !HARNESS_ENV.has(k) ? "__ENV__" : pub(v))}`),
    "",
  ];
  return lines.join("\n");
}

/** A checked word for the TOML and the command line: Vibe's model aliases and thinking levels are plain names. */
const plain = (what, v) => {
  if (v === undefined || v === null || v === "") return null;
  if (!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,99}$/.test(String(v))) throw new Error(`${what} ${JSON.stringify(String(v)).slice(0, 60)} is not a plain name`);
  return String(v);
};

/**
 * `aas options`: the models and thinking levels as Vibe itself names them (vibe-acp, `session/new`: no prompt, no
 * model call). A model outside that list is refused, because `active_model` must name one Vibe knows.
 */
export async function vibeOptions() {
  const o = await askVibe();
  return {
    source: `Mistral Vibe ${o.version ?? ""} itself (vibe-acp session/new)`.replace("  ", " "),
    models: o.models.map((m) => ({ id: m.id, label: m.label, efforts: o.efforts, defaultEffort: o.effort })),
    current: o.model,
    currentEffort: o.effort,
    freeModel: null,
    efforts: o.efforts,
  };
}

/** Whether the installed vibe still offers the legacy harness (`vibe --help`). */
export function legacyHarness() {
  const r = spawnSync("vibe", ["--help"], { encoding: "utf8", timeout: 20000 });
  return r.status === 0 && /--legacy-harness/.test(`${r.stdout}${r.stderr}`);
}

/** Every stream file of a run directory's sessions: what the proof covers and what `aas publish` exports. */
const streamOf = (runDir) => path.join(path.resolve(runDir), STREAM_FILE);

export default {
  id: "mistral-vibe",
  /** a model plays. */
  ai: true,
  name: "Mistral Vibe",
  version: "0.34.5",
  /** Its CLI: `aas gui` offers the runtime when this is on the PATH. */
  cli: "vibe",
  /** The Setup tab's button: Mistral's own installer (it installs uv, pinned and checked by sha256, then mistral-vibe). */
  setup: {
    group: "Agents",
    // Vibe keeps no plan budget the tooling can read, so every run is held to a price (vibe --max-price).
    settings: [{ env: "AAS_VIBE_MAX_PRICE", label: "Most a session may cost (dollars)", kind: "text", what: "The most one Vibe session of a run may cost, in dollars, as Vibe counts it (vibe --max-price). A run does not start without it." }],
    fixes: { install: { label: "Install Mistral Vibe", command: ["bash", "-c", "curl -LsSf https://mistral.ai/vibe/install.sh | bash"] } },
  },
  async options() { return vibeOptions(); },
  /** The run's own log (the stream Vibe printed, with its arrival times), and the sessions Vibe itself saved for this directory. */
  sessionLogs(runDir) {
    const own = fs.existsSync(streamOf(runDir)) ? [streamOf(runDir)] : [];
    const dir = path.join(vibeHome(), "logs", "session");
    let saved = [];
    try {
      saved = fs.readdirSync(dir).filter((d) => d.startsWith("session_")).map((d) => path.join(dir, d)).filter((d) => {
        try { return path.resolve(JSON.parse(fs.readFileSync(path.join(d, "meta.json"), "utf8")).environment?.working_directory ?? "") === path.resolve(runDir); } catch { return false; }
      }).flatMap((d) => ["messages.jsonl", "meta.json"].map((f) => path.join(d, f)).filter((f) => fs.existsSync(f)));
    } catch { /* no saved sessions */ }
    return [...own, ...saved];
  },
  findSession(runDir) { return fs.existsSync(streamOf(runDir)) ? streamOf(runDir) : null; },
  /** Read-only checks for `aas doctor`: vibe on the PATH, its folder, a key, and the price limit every run needs. */
  async doctor() {
    const rows = [];
    const v = spawnSync("vibe", ["--version"], { encoding: "utf8" });
    rows.push({ ok: v.status === 0, what: "Mistral Vibe on PATH", detail: v.status === 0 ? v.stdout.trim() : "vibe not found", level: "missing", fix: "install" });
    if (v.status !== 0) return rows;
    const home = vibeHome();
    const legacy = legacyHarness();
    rows.push({ ok: legacy, what: "it offers --legacy-harness (the harness whose tool filter holds)", detail: legacy ? "" : "This Vibe has no --legacy-harness; runs through it cannot be limited to the broker's three tools." });
    rows.push({ ok: fs.existsSync(home), what: `its folder is there (${home})`, detail: fs.existsSync(home) ? "" : "Not set up: vibe --setup" });
    let key = Boolean(process.env.MISTRAL_API_KEY);
    try { key ||= /^MISTRAL_API_KEY=\S+/m.test(fs.readFileSync(path.join(home, ".env"), "utf8")); } catch { /* no .env */ }
    rows.push({ ok: key, what: "MISTRAL_API_KEY is set", detail: key ? "" : "Not set: vibe --setup", level: "warn" });
    const price = process.env.AAS_VIBE_MAX_PRICE;
    // A setting of this machine, so a condition of the set-up: without it no Vibe run starts.
    rows.push({ ok: Number(price) > 0, what: "AAS_VIBE_MAX_PRICE is set (the most a session may cost, in dollars: vibe --max-price)", detail: Number(price) > 0 ? `${price}` : "Not set: a run does not start without it (Vibe keeps no plan budget the tooling can read).", level: "warn" });
    return rows;
  },
  /**
   * Does the run's configuration give the agent the broker? Vibe has no command that lists its MCP servers outside a
   * session, so this starts the server exactly as the run's .vibe/config.toml names it and asks it for its tools
   * (an MCP handshake, no model call).
   */
  async connectCheck(runDir, { gameId } = {}) {
    const { checkConfiguredServer } = await import("./connect-check.mjs");
    return checkConfiguredServer(runDir, { expect: ["documentation", "screenshot", "exec"].map((t) => `${gameId}_${t}`) });
  },
  async exportSession(session, outDir, { completionMarker } = {}) {
    const { exportStream } = await import("./export-stream.mjs");
    await exportStream(session, outDir, { completionMarker: completionMarker ?? process.env.AAS_COMPLETION_MARKER ?? null });
  },
  async configure(runDir, broker, brief) {
    const config = path.join(runDir, ".vibe", "config.toml");
    const instructions = path.join(runDir, "AGENTS.md");
    for (const f of [config, instructions]) if (fs.existsSync(f)) throw new Error(`Refusing to overwrite ${f}`);
    const model = plain("model", brief.model);
    const effort = plain("thinking", brief.reasoningEffort);
    fs.mkdirSync(path.dirname(config), { recursive: true });
    fs.writeFileSync(config, renderConfig(broker, { model, effort }), { flag: "wx" });
    fs.writeFileSync(instructions, brief.instructions, { flag: "wx" });
    fs.mkdirSync(path.join(runDir, "runtime-config"), { recursive: true });
    fs.writeFileSync(path.join(runDir, "runtime-config", "config.template.toml"), renderConfig(broker, { model, effort, placeholders: true }), { flag: "wx" });
    return { files: [config, instructions], hint: `Run: aas start --runtime mistral-vibe --run-dir ${runDir}` };
  },
  async writePublicConfig(runDir, broker) {
    const brief = (() => { try { return JSON.parse(fs.readFileSync(path.join(runDir, "brief.json"), "utf8")); } catch { return {}; } })();
    fs.mkdirSync(path.join(runDir, "runtime-config"), { recursive: true });
    fs.writeFileSync(path.join(runDir, "runtime-config", "config.template.toml"), renderConfig(broker, { model: plain("model", brief.model), effort: plain("thinking", brief.reasoningEffort), placeholders: true }));
  },
  /** Rewrite the configuration (absolute paths) when the run directory moved; the instructions are kept. */
  async reconfigure(runDir, broker, brief = {}) {
    fs.mkdirSync(path.join(runDir, ".vibe"), { recursive: true });
    fs.writeFileSync(path.join(runDir, ".vibe", "config.toml"), renderConfig(broker, { model: plain("model", brief.model), effort: plain("thinking", brief.reasoningEffort) }));
  },
  interrupt(reason) { interruptChild?.(reason); },
  /**
   * Interactive by default (vibe in the run directory). Headless: `vibe -p <prompt> --output streaming` with only the
   * three tools enabled, approved without asking (they are the only ones), the turn limit and the price limit, and
   * `--resume <session>` at a resume. Every entry Vibe streams is kept with the time it arrived.
   */
  async start(runDir, brief, { stopRequested = null } = {}) {
    const headless = brief.headless === true || !process.stdin.isTTY;
    const gameId = brief.category?.game ?? brief.game?.id;
    if (!gameId) throw new Error("The run's brief names no game.");
    if (!headless) {
      const child = spawn("vibe", ["--trust", ...(brief.goalPrompt ? [brief.goalPrompt] : [])], { cwd: runDir, stdio: "inherit" });
      const code = await new Promise((res, rej) => { child.on("error", (e) => rej(new Error(`Could not start vibe: ${e.message}`))); child.on("close", res); });
      return { status: code === 0 ? "completed" : "failed", endedAt: new Date().toISOString(), notes: `vibe exited with ${code}` };
    }
    const prompt = brief.resume ? brief.resume.prompt : brief.goalPrompt;
    if (!prompt) throw new Error("Headless runs need a goal prompt (aas configure --prompt, or goalPrompt in the game plugin).");
    const price = Number(process.env.AAS_VIBE_MAX_PRICE);
    if (!(price > 0)) throw new Error("AAS_VIBE_MAX_PRICE is not set: a Vibe session needs the most it may cost, in dollars (vibe --max-price), because Vibe keeps no plan budget the tooling can read. Set it in .env.");
    // The legacy harness, by Vibe's own flag: in it `--enabled-tools` disables every other tool in -p mode (its source,
    // vibe/cli/entrypoint.py). The unified harness 2.25.8 runs by default kept its own tools (bash, read_file, process.*,
    // subagents; measured in the smoke session of 2026-09-29 20:28), so it is not used until its filter is proven.
    if (!legacyHarness()) throw new Error("This Mistral Vibe has no --legacy-harness: the tooling cannot hold its tools to the broker's three, so the run does not start.");
    const args = ["-p", prompt, "--legacy-harness", "--output", "streaming", "--trust", "--workdir", runDir, "--auto-approve", "--max-price", String(price),
      ...toolNames(gameId).flatMap((t) => ["--enabled-tools", t])];
    if (brief.budget?.toolCalls) args.push("--max-turns", String(brief.budget.toolCalls));
    if (brief.resume?.sessionId) args.push("--resume", String(brief.resume.sessionId));
    const version = spawnSync("vibe", ["--version"], { encoding: "utf8" }).stdout?.trim() ?? null;
    const stream = fs.createWriteStream(streamOf(runDir), { flags: "a" });
    stream.write(`${JSON.stringify({ receivedAt: new Date().toISOString(), vibe: { version, model: brief.model ?? null, thinking: brief.reasoningEffort ?? null, resume: brief.resume?.sessionId ?? null } })}\n`);
    const child = spawn("vibe", args, { cwd: runDir, env: process.env, stdio: ["ignore", "pipe", "pipe"] });
    let sessionId = brief.resume?.sessionId ?? null, messages = 0, toolCalls = 0, lastError = null, gameOver = null, timedOut = false;
    const stop = () => { child.kill("SIGINT"); setTimeout(() => { if (child.exitCode === null) child.kill("SIGTERM"); }, 60000).unref(); };
    interruptChild = (reason) => { gameOver = reason; process.stderr.write(`[runtime-mistral-vibe] ${reason}; interrupting the session\n`); stop(); };
    // A stop that came before this session existed (the harness asks; 2026-10-02: it was lost and a whole session ran).
    { const early = stopRequested?.(); if (early) interruptChild(early); }
    const minutes = Number(brief.budget?.minutes) || 0;
    const deadline = minutes ? setTimeout(() => { timedOut = true; process.stderr.write(`[runtime-mistral-vibe] time budget of ${minutes} min reached; interrupting the session\n`); stop(); }, minutes * 60000) : null;
    let buf = "";
    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (d) => {
      buf += d;
      let at;
      while ((at = buf.indexOf("\n")) !== -1) {
        const line = buf.slice(0, at); buf = buf.slice(at + 1);
        if (!line.trim()) continue;
        let e; try { e = JSON.parse(line); } catch { continue; }
        stream.write(`${JSON.stringify({ receivedAt: new Date().toISOString(), entry: e })}\n`);
        sessionId = e.sessionId ?? sessionId;
        if (e.type === "message" && e.role === "assistant") { messages += 1; process.stderr.write(`[agent] ${(e.content ?? []).map((c) => c.text ?? "").join(" ").trim().split("\n")[0].slice(0, 160)}\n`); }
        if (e.type === "effect") { toolCalls += 1; process.stderr.write(`[agent] → ${e.detail?.toolName}${e.detail?.input?.code ? `: ${String(e.detail.input.code).replace(/\s+/g, " ").slice(0, 120)}` : ""}\n`); }
        if (e.type === "notice" && e.level === "error") lastError = e.message;
      }
    });
    child.stderr.setEncoding("utf8");
    child.stderr.on("data", (d) => { process.stderr.write(d); const l = d.trim().split("\n").at(-1); if (/error/i.test(l)) lastError = l.slice(0, 200); });
    const code = await new Promise((res, rej) => { child.on("error", (e) => rej(new Error(`Could not start vibe: ${e.message}. Install Mistral Vibe (the Setup tab, or curl -LsSf https://mistral.ai/vibe/install.sh | bash).`))); child.on("close", res); });
    if (deadline) clearTimeout(deadline);
    interruptChild = null;
    await new Promise((res) => stream.end(res));
    // Vibe ends a session that reached --max-turns or --max-price with an error of its own; that is a limit, so the
    // run can go on (a resume), not a failure.
    const limited = code !== 0 && /limit|max[-_ ]?(price|turns|tokens)|cost exceeds/i.test(lastError ?? "");
    const stopped = timedOut || Boolean(gameOver) || limited;
    const status = code === 0 && !stopped ? "completed" : stopped ? "stopped" : "failed";
    const notes = `vibe exited with ${code}; ${messages} agent messages, ${toolCalls} tool calls${lastError ? `; ${lastError}` : ""}${timedOut ? `; time budget of ${minutes} min reached` : ""}${gameOver ? `; ${gameOver}` : ""}`;
    return { status, endedAt: new Date().toISOString(), notes, sessionId, privateLog: streamOf(runDir) };
  },
};
